name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: erlef/setup-beam@v1.15.2
        with:
          otp-version: '24'
          gleam-version: '0.23.0'
      - run: |
          make
          make test
